import { useState, useEffect } from "react";
// import { useSession, getSession, signIn, signOut } from "next-auth/client";
import { useSession, getSession, signIn, signOut } from "next-auth/react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
export default function Home() {
  const [isLogedIn, setIsLogedIn] = useState();
  const { data: session, status } = useSession();

  useEffect(() => {
    console.log(session, status);
    return () => {};
  }, [session, status]);

  if (status === "loading") {
    return <div>Loading</div>;
  }

  const getStringDate = () => {
    var date = new Date(session.expires);
    console.log(date);

    return date.toISOString().substring(0, 10);
  };
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className=" container">
          <h1 className=" text-primary w-100 text-center">
            Next Js Basic Project
          </h1>
          <ul className=" list-unstyled text-info">
            <li className=" mb-3">
              <Link href="/posts">
                <a className=" text-decoration-none h3 text-info">Post</a>
              </Link>
            </li>
            <li className=" mb-3">
              <Link href="/todos">
                <a className=" text-decoration-none h3 text-info">Todos</a>
              </Link>
            </li>
            <li className=" mb-3">
              <Link href="/create-todo">
                <a className=" text-decoration-none h3 text-info">
                  Create Todos
                </a>
              </Link>
            </li>
          </ul>

          <div className=" row justify-content-center">
            <div className=" col-12 col-md-6">
              {session ? (
                <div className=" card">
                  <div className=" card-body d-flex align-items-center flex-column">
                    <img
                      src={session.user.image}
                      alt=""
                      style={{
                        height: "300px",
                        width: "300px",
                      }}
                      // className=" w-100 d-flex justify-content-center"
                    />

                    <h1>{session.user.name}</h1>

                    <h3>{session.user.email}</h3>
                    <p>{getStringDate()}</p>

                    <div onClick={() => signOut()} className=" btn btn-danger">
                      Sign Out
                    </div>
                  </div>
                </div>
              ) : (
                <div>
                  <div onClick={() => signIn()} className=" btn btn-dark">
                    {" "}
                    Sign In with Github
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
